fix error reporting when used in conjuction with ssh

diff --git a/local/bin/proxy b/local/bin/proxy
--- a/local/bin/proxy
+++ b/local/bin/proxy
@@ -17,7 +17,7 @@ if [ -n "${https_proxy}" ]; then
     # Debian etc.
     exec nc -X connect -x "${https_proxy}" "${HOST}" "${PORT}"
   else
-    echo "Error: CONNECT proxy command is not available."
+    echo "Error: CONNECT proxy command is not available." >&2
   fi
 else
   exec nc "${HOST}" "${PORT}"
